import type { ForecastMarket } from "./types";

export const ANALYST_TIER_LABELS = {
  rookie_analyst: "Rookie Analyst",
  trend_watcher: "Trend Watcher",
  market_scout: "Market Scout",
  senior_analyst: "Senior Analyst",
  top_analyst: "Top Analyst",
  community_oracle: "Community Oracle",
} as const;

export const DEMO_FORECAST_MARKETS: ForecastMarket[] = [
  {
    id: "demo-honey-banana",
    question: "Will Honey Banana remain Top 10 next week?",
    target_type: "product",
    product_slug: "honey-banana-local-grove",
    product_name: "Honey Banana",
    brand_slug: "local-grove",
    brand_name: "Local Grove",
    status: "open",
    closes_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    days_left: 3,
    yes_count: 297,
    no_count: 115,
    total_forecasts: 412,
    bullish_percent: 72,
    bearish_percent: 28,
    outcome: null,
    user_vote: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-superboof",
    question: "Will Superboof remain Top 10 next week?",
    target_type: "product",
    product_slug: "superboof-rkive",
    product_name: "Superboof",
    brand_slug: "rkive",
    brand_name: "RKIVE",
    status: "open",
    closes_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    days_left: 5,
    yes_count: 184,
    no_count: 96,
    total_forecasts: 280,
    bullish_percent: 66,
    bearish_percent: 34,
    outcome: null,
    user_vote: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-local-grove",
    question: "Will Local Grove gain momentum next week?",
    target_type: "brand",
    product_slug: null,
    product_name: null,
    brand_slug: "local-grove",
    brand_name: "Local Grove",
    status: "open",
    closes_at: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    days_left: 4,
    yes_count: 142,
    no_count: 88,
    total_forecasts: 230,
    bullish_percent: 62,
    bearish_percent: 38,
    outcome: null,
    user_vote: null,
    created_at: new Date().toISOString(),
  },
];
